version: '3.7'

volumes:
  postgres_data:

services:
  db:
    image: postgres:12.0-alpine
    volumes:
    - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    ports:
    - 8080:8080



